### ISSUE TITLE
Preparing metadata error when doing pip install

### ISSUE THREAD

**Issue by dfelikson** [rgerum/pylustrator#41]
I'm trying to pip install pylustrator and getting an error (see below for output). I have macOS 12.4 and installing to a fresh conda environment.

```
Collecting pylustrator
  Using cached pylustrator-1.1.2-py3-none-any.whl (140 kB)
Collecting pyqt5
  Using cached PyQt5-5.15.7.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "/Users/dfelikso/Software/miniconda/miniconda3/envs/pylustrator/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "/Users/dfelikso/Software/miniconda/miniconda3/envs/pylustrator/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/Users/dfelikso/Software/miniconda/miniconda3/envs/pylustrator/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/dfelikso/Software/miniconda/miniconda3/envs/pylustrator/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-install-5_ynaead/pyqt5_22e615225c734d568c943d96994bf865/project.py", line 69, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/sipbuild/project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/ny/tt_x0grn03z19yx_r4p_57c80000gq/T/pip-build-env-sjp7jwzq/overlay/lib/python3.10/site-packages/pyqtbuild/builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by rgerum** [comment]
It seems to be an error with installing PyQt5. Maybe you could try to install a different version of PyQt5? I don't have a mac around to test the installation there.

**Comment by rgerum** [comment]
I fixed a couple of errors for the release I just published. Maybe your problem is solved now. If the problem persists feel free to open the issue again.
