### ISSUE TITLE
Misc `not found`, `not in list` errors

### ISSUE THREAD

**Issue by tfiers** [rgerum/pylustrator#52]
Hi, this project is a great idea.

I get errors when trying to add text to an axis:
```
Traceback (most recent call last):
  File "C:\conda\lib\site-packages\pylustrator\components\qitem_properties.py", line 1019, in buttonAddTextClicked
    getReference(self.element), getReference(text)), text, ".new")
  File "C:\conda\lib\site-packages\pylustrator\change_tracker.py", line 162, in getReference
    raise TypeError(str(type(element)) + " not found")
TypeError: <class 'matplotlib.text.Text'> not found
```
or add an arrow:
```
Traceback (most recent call last):
  File "C:\conda\lib\site-packages\pylustrator\components\qitem_properties.py", line 1085, in buttonAddArrowClicked
    p._posA_posB[0], p._posA_posB[1], getReference(p)),
  File "C:\conda\lib\site-packages\pylustrator\change_tracker.py", line 104, in getReference
    index = element.axes.patches.index(element)
ValueError: <matplotlib.patches.FancyArrowPatch object at 0x0000017A2D76B820> is not in list
```
or change a Line2D's property:
```
<matplotlib.lines.Line2D object at 0x000001F3198B2160> is not in list
```

The edits are displayed in the plot, but are not saved to the .py file.

pylustrator version 1.2.1
matplotlib version 3.5.1

**Comment by rgerum** [comment]
its a problem with the exception_silencer and the recent matplotlib version. You can turn it of with:

`pylustrator.start(use_exception_silencer=False)`

with I will make the default in the next release

**Comment by tfiers** [comment]
That fixes it indeed, thanks!
