### ISSUE TITLE
ModuleNotFoundError: No module named 'matplotlib.axes._subplots'

### ISSUE THREAD

**Issue by hackerzone85** [rgerum/pylustrator#59]
```
(biotite) ddalab@DP7820-WS:Analysis$ python -c 'import pylustrator'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ddalab/anaconda3/envs/biotite/lib/python3.11/site-packages/pylustrator/__init__.py", line 22, in <module>
    from .QtGuiDrag import initialize as start
  File "/home/ddalab/anaconda3/envs/biotite/lib/python3.11/site-packages/pylustrator/QtGuiDrag.py", line 33, in <module>
    from .ax_rasterisation import rasterizeAxes, restoreAxes
  File "/home/ddalab/anaconda3/envs/biotite/lib/python3.11/site-packages/pylustrator/ax_rasterisation.py", line 24, in <module>
    from matplotlib.axes._subplots import Axes
ModuleNotFoundError: No module named 'matplotlib.axes._subplots'

**Comment by rgerum** [comment]
which matplotlib version are you using?

**Comment by rgerum** [comment]
ok it appears to have been introduced in matplotlib version 3.6.0
